name: Update docs

on: push

jobs:
  update-readme:
    name: Update docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install Neovim and dependencies
        env:
          NVIM_TAG: v0.8.0
        run: |
          bash ./.github/workflows/install_nvim.sh

      - name: Update docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: |
            [docgen] Update docs
            skip-checks: true
        run: |
          git config user.email "actions@github"
          git config user.name "Github Actions"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          python -m pip install pyparsing
          python .github/main.py generate
          python .github/main.py lint
          nvim --headless -c 'set runtimepath+=.' -c 'helptags ALL' -c 'qall'
          git add README.md doc
          # Only commit and push if we have changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin HEAD:${GITHUB_REF})
